### PR TITLE
Limit ansible to only use kitchen (or otherwise specified) key

### LINKED ISSUE #19: '--ssh-extra-args="-o IdentitiesOnly=yes"' should be included by default
Even when you specify a private key, `ssh` will still try to iterate through the keys in a user's .ssh directory unless the IdentitiesOnly flag is set to yes.  As a result, `ssh` as called by ansible will make several failed connection attempts before it finally hits the key specified as `--private-key` or in the ENV variable.  

While that's fine when sshd is set up to accept multiple attempts, once you have set MaxAuthTries to 1 (in sshd.conf), ansiblepush fails because ansible doesn't get a second bite at the cherry.

This setting is already used for net-ssh for the `kitchen login` command, so that still works (it's config param `:keys_only => true`), but of course that isn't used for the ansible run, leading to inconsistent behaviour where kitchen login works but kitchen converge (using ansiblepush) doesn't.  

As a workaround I am using `raw_arguments: '--ssh-extra-args="-o IdentitiesOnly=yes"'` in my `.kitchen.yml` file.

The proper fix would probably be to include `--ssh-extra-args="-o IdentitiesOnly=yes"` when you're building the options string (somewhere around line 118 of `ansible_push.rb`)

### PR DESCRIPTION
**Pull request by j4m3s**
Closes #19

### CODE REVIEW

**Comment by ahelal** [comment]
Hi.

I would rather have something like this 

``` ruby
if conf[:ssh_extra_args]
    options << "--ssh-extra-args=#{conf[:ssh_extra_args]}"
else
    # Default only use the specific kitchen ssh key
    options << "--ssh-extra-args='-o IdentitiesOnly=yes'"   
fi
```

Just to give option to change the default behaviour

**Comment by neillturner** [comment]
@j4m3s james sorry to interrupt your request but it would be really good if you could write a blog post on how you use ansiblepush and my verifier serverspec to do devops totally remotely so that the server is not polluted with any devops software and works well as a container. I think this is a use case that will increasingly be used by folks in the future, So really appreciate if you could blog on it to show folks what to do.

**Comment by j4m3s** [comment]
@ahelal I'm worried now, seeing the CI build fail.  I suspect the ansible default behaviour changed when the implemented v 2.1 - so they used to include `IdentitiesOnly=yes` by default, but no longer do.  At the same time, they've introduced the `--ssh-extra-args`.

I don't develop in Ruby so wouldn't be able to code-in a version check to only add `--ssh-extra-args` for ansible v2.1 or above.  I suggest therefore that I update the PR to add the ssh_extra_args config parameter, but don't set it to anything by default.  Maybe I put a note in the README saying it should be set to `IdentitiesOnly=yes` for people using ansible v2.1 or above?  Either that or you can tell me what to include so it does an ansible version check and chooses a sane default appropriate to the version?

On which note, your travis check should prob be updated to include v2.1 now it's been released.  I think that means changing another repo too but couldn't be sure.

@neillturner you're right, a blog post would be valuable, I'll look into it.  Need to decide where to post it.

**Comment by ahelal** [comment]
@j4m3s I  think --ssh-extra-args is in 2.x
I am a little bit busy this week, but if you cant manage will try to get it in the weekend. And I can make tests for 1.x, 2.0.x and 2.1.x just to be in the safe side

**Comment by ahelal** [comment]
I will close this in favour of adding #37  that will support 'ssh-extra-args', but no default since this might break for other people. I would suggest adding your config in .kitchen.yml https://github.com/ahelal/kitchen-ansiblepush/pull/37/files#diff-ceadf4973eed26a4a9694bb7fb30b128R55.

**Pull request closed without merging**
